### PR TITLE
Channel description

### PR DESCRIPTION
**Pull request by mymikemiller**
I needed access to a channel's description from the channel's About page, so I added it to the library. 

Not sure if this is the most efficient way of getting the full description. Part of the description is available at the #description selector on the channel page that is already fetched, but it's not the full description that I was only able to find by fetching the "About" page.

### CODE REVIEW

**Review by Hexer10 — APPROVED** [review]
Thanks for the PR I really like the implementation, the only thing that could be missing is that there are no unit tests on this feature, if you are able to add one it would be nice, otherwise I can do it

**Comment by Hexer10** [comment]
Since the channel about page contains lots of information other than just the channel description (such as the channel views,  channel links, etc.) I'm going to implement most of them in the next version

**Comment by mymikemiller** [comment]
Thanks for accepting the PR. Glad I could contribute to the library; I'm excited to see what the next version brings in regards to making extra channel information available!

**Comment by mymikemiller** [comment]
@Hexer10 Are we any closer to seeing this functionality in the main branch? I'm currently using a fork that includes my change, as it's necessary for my work.

**Comment by Hexer10** [comment]
Sorry, I forgot about this, I'll take the time to implement this by the next week.

**Comment by Hexer10** [comment]
@mymikemiller I've implemented it, you can check its usage here:
https://github.com/Hexer10/youtube_explode_dart/blob/5e6aa737cbf1e6d190dc9203499ee8283730babb/test/channel_test.dart#L68-L74

**Comment by mymikemiller** [comment]
This works great, thanks @Hexer10!

I'm not sure if it was this change as it seems unrelated, but I'm now unable to get *video* descriptions when fetched through the channel uploads api.

This works:
```
  final yt = YoutubeExplode();
  var video = await yt.videos.get('https://youtube.com/watch?v=YP_nB6QlDFc');
  var description = video.description; // Contains actual description
```

This doesn't:
```
  final yt = YoutubeExplode();
  final stream = yt.channels.getUploads("UCNl_4FD4qQdZZJMzAM7LJqQ");
  final Video video = await stream.first;
  final description = video.description; // Contains ""
```

**Comment by Hexer10** [comment]
Hasn't it always been the case? Unfortunately when you go thought the channel uploads page there are no video descriptions available.

**Comment by mymikemiller** [comment]
Hmm. I thought it used to work for me. So the only option is to do another get for each video individually?

```
  final stream = yt.channels.getUploads("UCNl_4FD4qQdZZJMzAM7LJqQ");
  final Video incompleteVideoObject = await stream.first;
  final Video fullVideoObject = await yt.videos.get(incompleteVideoObject.id);
  var description = fullVideoObject.description;
```

**Comment by mymikemiller** [comment]
This probably isn't the right place for this discussion, but are there any other attributes of channel upload Videos that are different from individually-fetched Videos?

I noticed that the upload's uploadDate is null and the video's uploadDate has the correct date, but not the correct time (everything is at midnight). I'm more interested in the publish date anyway, but [this](https://github.com/Hexer10/youtube_explode_dart/issues/68) hasn't been merged. I'll work on updating that code unless you have an easier way for me to get the publish date of a video.

**Comment by mymikemiller** [comment]
There was an easier way to get the publishDate - it was practically already there! [This PR](https://github.com/Hexer10/youtube_explode_dart/pull/74) exposes it.

In any case, channel descriptions are working perfectly, thanks for implementing!

**Comment by Hexer10** [comment]
> This probably isn't the right place for this discussion, but are there any other attributes of channel upload Videos that are different from individually-fetched Videos?
> 
> I noticed that the upload's uploadDate is null and the video's uploadDate has the correct date, but not the correct time (everything is at midnight).

This happens because the uploadDate is retrivied by doing DateTime.now() - X ago it was published (ie DateTime.now() - 5days), since Youtube doesn't expose the exact uploadDate as can be seen here:
image

**Pull request merged**
